options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
  # Pull cached base image if it exists
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull gcr.io/$PROJECT_ID/restful-webserver:base || exit 0
  # Rebuild base image (with gcovr added in base.Dockerfile)
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "docker/base.Dockerfile",
        "-t",
        "restful-webserver:base",
        "-t",
        "gcr.io/$PROJECT_ID/restful-webserver:base",
        "--cache-from",
        "gcr.io/$PROJECT_ID/restful-webserver:base",
        ".",
      ]
  # Push base image to registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/restful-webserver:base"]
  # Build main project container
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "CONFIG_FILE=cloud_config.txt",
        "-f",
        "docker/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/restful-webserver:latest",
        ".",
      ]
  # Run coverage check container
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-f", "docker/coverage.Dockerfile", "-t", "coverage-check", "."]
images:
  [
    "gcr.io/$PROJECT_ID/restful-webserver:base",
    "gcr.io/$PROJECT_ID/restful-webserver:latest",
  ]
